language: php

php:
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpstan analyse -l 4 src tests
    - php vendor/bin/phpcs --standard=PSR1,PSR2 src tests

notifications:
    email: false